### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by Randall94** [bhamodi/facebook-online-friend-tracker#4] opened 2015-12-08 19:09 UTC
So I finally managed to get my hands on this awesome stuff, but my excitement ended after this error:

```
Starting script...
Verifying that the CSV file exists...
[WARNING] 'C:\fb.csv' does not exist. Creating a new CSV file now...
New CSV file created at: C:\Python27\Scripts\facebook_online_friend_tracker_data.csv

Initializing Chrome WebDriver...
Logging into Facebook...
Waiting for Facebook to update friends list... (This takes approximately 2 minutes.)
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\facebook-online-friend-tracker.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\src\main.py", line 75, in main
    onlineFriendsCount = int(driver.find_element_by_xpath('//*[@id="fbDockChatBuddylistNub"]/a/span[2]/span').text.strip('()'))
ValueError: invalid literal for int() with base 10: ''
```

As it seems to work for others, I guess it's a problem in my folder structure or something similar ?
Thank you.

**Comment by bhamodi** [comment] 2015-12-09 03:51
Hey @Randall94 - thanks for submitting this! I've just pushed out a potential fix for this. I wasn't able to reproduce the issue locally but from the stack trace you've shared - there are two possibilities. One possibility is that no friends were online during the time the script was being run and as such the script crashed trying to convert an empty string to an integer. Or, worse, the script failed to extract the number of online friends from the char bar. Could you please try out the new version (`v1.2.3`)? Also please let me know if you can see this when the Chrome browser is open: 
<img width="296" alt="screen shot 2015-12-08 at 10 46 40 pm" src="https://cloud.githubusercontent.com/assets/7663987/11676187/193b21e8-9dfe-11e5-86ee-7a7ae878b9b8.png">

**Comment by Randall94** [comment] 2015-12-09 09:25
cool! Thanks a lot. 
Now it does work indeed, however the .csv file output is somehow messed up. I can't think of any reason why it's outputting completely different data then it should, hah..

Done! Detected 59 online friends.
Added: 2015/12/09 10:20:37 -> 59 to the spreadsheet.

![capture](https://cloud.githubusercontent.com/assets/15701020/11681400/0ebda252-9e5f-11e5-945b-615ee27d24af.PNG)

**Comment by bhamodi** [comment] 2015-12-09 14:21
Hmm, just tested the latest version on both Windows and OS X, I can't seem to reproduce that issue. Could you please try again on a clean CSV file and provide me with more information if the issue persists? Thanks.

**Comment by Randall94** [comment] 2015-12-09 14:55
I tried several times, both with letting the script creating a new csv file and also with a csv file created by me in advance.. Exact same result as above. As I mentioned, it looks like the formatting is somehow messed up. As you can see on the screenshot, the field has bs values (format is custom), but when highlighted, it shows correct date and time. But it's weird, as it works for you..

**Comment by bhamodi** [comment] 2016-02-03 19:30
Hey @Randall94 - are you still having problems with the latest version?
Please run `pip install facebook-online-friend-tracker --upgrade` and let me know. Thanks!

**Comment by Randall94** [comment] 2016-02-06 12:13
Hey @bhamodi . Thanks for the update. 
Well, now the time and number of friends format is correct in the csv, but it tells me there's 0 friends online - which obviously is not.

**Comment by bhamodi** [comment] 2016-03-21 03:18
Closing this task because the 0 friends issue is being tracked here: #5

**Closed as completed by bhamodi** 2016-03-21 03:18 UTC
