### ISSUE TITLE
Can't run script

### ISSUE THREAD

**Issue by lorenzoPrimi** [bhamodi/facebook-online-friend-tracker#2] opened 2015-07-19 20:07 UTC
Which configuration did you use?
I tried to run on a raspberry pi and a debian web server (without X)
I get the following error messages

Verifying that the CSV file exists...
[WARNING] test.csv does not exist. Creating a new CSV file now...
New CSV file created at: /home/pi/facebook_online_friend_tracker_data.csv

Initializing Chrome WebDriver...
Traceback (most recent call last):
  File "/usr/local/bin/facebook-online-friend-tracker", line 9, in <module>
    load_entry_point('facebook-online-friend-tracker==1.2.1', 'console_scripts', 'facebook-online-friend-tracker')()
  File "/usr/local/lib/python2.7/dist-packages/src/main.py", line 39, in main
    driver = webdriver.Chrome()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 62, in **init**
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/service.py", line 68, in start
    self.service_args, env=env, stdout=PIPE, stderr=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 679, in **init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1259, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

---

Initializing Chrome WebDriver...
Traceback (most recent call last):
  File "/usr/local/bin/facebook-online-friend-tracker", line 9, in <module>
    load_entry_point('facebook-online-friend-tracker==1.2.1', 'console_scripts', 'facebook-online-friend-tracker')()
  File "/usr/local/lib/python2.7/dist-packages/src/main.py", line 39, in main
    driver = webdriver.Chrome()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 68, in **init**
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 89, in **init**
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 138, in start_session
    'desiredCapabilities': desired_capabilities,
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 195, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 170, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Driver info: chromedriver=2.16.333243 (0bfa1d3575fc1044244f21ddb82bf870944ef961),platform=Linux 3.13.0-54-generic x86_64)

**Comment by bhamodi** [comment] 2015-07-20 06:20
Interesting... It seems like ChromeDriver is not found. So - I am using an external library for configuring/installing ChromeDriver automatically for users as it is a good UX. This is the library being used: https://pypi.python.org/pypi/chromedriver_installer
I think the issue is that the library does not account for your environment setup (Raspberry Pi and a Debian web server). Could you try installing and setting up ChromeDriver [manually](https://sites.google.com/a/chromium.org/chromedriver/)?

**Comment by lorenzoPrimi** [comment] 2015-07-20 07:59
On my X86_64 server i get this error, while on the raspb pi there is no binary for chromedriver I would have to complie it manually. Can you tell me which OS did you use to run the script and I try to reproduce your environment ?
Thanks

Last error:
Initializing Chrome WebDriver...
Traceback (most recent call last):
  File "/usr/local/bin/facebook-online-friend-tracker", line 9, in <module>
    load_entry_point('facebook-online-friend-tracker==1.2.1', 'console_scripts', 'facebook-online-friend-tracker')()
  File "/usr/local/lib/python2.7/dist-packages/src/main.py", line 39, in main
    driver = webdriver.Chrome()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 68, in **init**
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 89, in **init**
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 138, in start_session
    'desiredCapabilities': desired_capabilities,
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 195, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 170, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.16.333243 (0bfa1d3575fc1044244f21ddb82bf870944ef961),platform=Linux 3.13.0-54-generic x86_64)

**Comment by bhamodi** [comment] 2015-07-20 16:31
@lorenzoPrimi - I've run this tool on both OS X Yosemite and Windows 7.

**Comment by lorenzoPrimi** [comment] 2015-07-20 17:16
Works perfectly on OS X. Thanks.
Maybe if you have time check it on linux and see what went wrong.

**Comment by bhamodi** [comment] 2015-07-21 00:02
Ya, @lorenzoPrimi - I'll definitely take a look into it. I would love for this script to work on any platform. Could you give me the exact OS properties for me to reproduce what you initially experienced?

**Comment by lorenzoPrimi** [comment] 2015-07-21 10:27
First (and third) error on a Ubuntu 12.04.3 LTS 64bit server without graphic interface (xorg not installed, I guess is needed to open chrome right?)
The second on a raspberry pi with last raspbian installed.
I'm gonna install a local machine like the first one locally and try if with xorg is gonna work.

**Comment by bhamodi** [comment] 2015-07-21 16:36
Awesome thanks for the help @lorenzoPrimi! It is appreciated.
I would assume not having a display interface would definitely cause problems with ChromeDriver.

**Comment by bhamodi** [comment] 2015-09-14 19:47
Any updates on this @lorenzoPrimi?

**Comment by lorenzoPrimi** [comment] 2015-09-14 21:17
On an Ubuntu 14.04 I get the "Cannot find Chrome binary" error but chromium-browser is installed and chromium-chromedriver also

**Comment by bhamodi** [comment] 2015-09-17 03:16
So @lorenzoPrimi, you're saying that [this step](https://github.com/peterhudec/chromedriver_installer) is working perfectly fine on Ubuntu? Are you able to run the above dependency? I suspect that that there may be some issue with where it is getting installed, if at all it does get installed.

**Comment by edevena** [comment] 2015-09-17 07:26
hello, are you considering leaving Chrome open and write the logfile 
every x minutes without exit? It happens often that chromium or 
chrome-driver hangs. Now the loop is

or (( ; ; ))
do

  facebook-online-friend-tracker --user 'edevena@gsy.it' --pass 
'Hyperion123' --path '/var/www/html/csv_file.csv'
  sleep 900
  /usr/bin/killall -9 chromium-browser
  /usr/bin/killall -9 chrome-sandbox
  /usr/bin/killall -9 chromedriver
  sleep 10
done

but still sometimes "facebook-online-tracker" hangs starting and I will 
have to create another tasks outside the shell. I think this may be 
supervised leaving chromium open and writing statistics without exiting.
Eugenio

Il 17/09/2015 05:16, Baraa Hamodi ha scritto:

**Comment by bhamodi** [comment] 2016-01-18 10:04
@lorenzoPrimi - closing this for now since the tool runs on the main supported platforms.
@edevena - that is a cool approach. I'm having a hard time deciding whether a user would want to have a Chrome window open at all times or whether a user would prefer to have a scheduled task. I would like more feedback from the community before making a big change like that.

**Closed as completed by bhamodi** 2016-01-18 10:04 UTC
