### ISSUE TITLE
Added 0 to the spreadsheet

### ISSUE THREAD

**Issue by enricopal** [bhamodi/facebook-online-friend-tracker#5] opened 2016-01-09 17:44 UTC
The script has worked fine for a few days, but now it always detects 0 friends online, even when it is clearly not the case. Any clue why this would happen?

**Comment by bhamodi** [comment] 2016-02-03 19:30
Hey @enricopal - is this issue still reproducible with the latest version??
Run `pip install facebook-online-friend-tracker --upgrade` and let me know. Thanks!

**Comment by enricopal** [comment] 2016-02-03 20:25
Yes, unfortunately! I'm using Ubuntu 14.04 on a Dell Inspiron

**Comment by bhamodi** [comment] 2016-02-03 20:29
Could you upload a screenshot of the Chrome browser while the tool is running? I suspect that the chat bar is not visible for some reason.

**Comment by enricopal** [comment] 2016-02-03 20:33
Indeed. A pop up asks me to authorize facebook to send me notifications. 
![schermata del 2016-02-03 21 33 00](https://cloud.githubusercontent.com/assets/16625821/12796165/ba570be6-cabd-11e5-862b-befb9c8b2d5a.png)

**Comment by bhamodi** [comment] 2016-02-03 20:53
Ah, I see the issue. The pop up isn't a problem, the tool will still work with it there. The issue is your chat bar. Notice how it doesn't look like this: 
<img width="312" alt="screen shot 2016-02-03 at 12 46 50 pm" src="https://cloud.githubusercontent.com/assets/7663987/12796547/399c935c-ca74-11e5-937f-065f37dcfd3d.png">

The chat bar only looks like this when the browser window is smaller. The tool is supposed to resize your browser window for you on line 72: `driver.set_window_size(700, 700)`

However, it appears that your window isn't resizing? This seems to be a problem with ChromeDriver on Ubuntu. A manual fix for this would be to resize your browser window until you can see the above chat bar. I'll look into why your browser isn't being resized.

**Comment by enricopal** [comment] 2016-02-03 21:06
Actually, I had enlarged the window to better show you, I didn't think that could be an issue. This is what it actually looks like 
![schermata del 2016-02-03 22 06 20](https://cloud.githubusercontent.com/assets/16625821/12797004/3374406c-cac2-11e5-924d-3e731728abc7.png)

**Comment by bhamodi** [comment] 2016-02-04 00:05
Ahh, weird... Are you able to minimize the chat bar for the time being?

**Comment by enricopal** [comment] 2016-02-04 08:45
yeah, it is weird... if I manually minimize the chat, it works fine, but by default it's open

**Comment by melaur** [comment] 2016-03-19 13:49
> How often would you like to check how many friends are online? Enter a number between 5 and 30 minutes: 6
> How long would you like to run this tool for? Enter a number between 1 and 720 hours: 1
> Path to the CSV file: C:\Users\Laur\Documents\fb-dvlaur.cvs
> Verifying that the CSV file exists...
> C:\Users\Laur\Documents\fb-dvlaur.cvs has been found.
> 
> Initializing Chrome WebDriver...
> Logging into Facebook...
> 
> Waiting for Facebook to update friends list... (This takes approximately 3 minutes.)
> Done! Detected 0 online friends.
> Added: 2016/03/19 15:33:17 -> 0 to the spreadsheet.
> 
> Waiting for Facebook to update friends list... (This takes approximately 3 minutes.)
> Done! Detected 0 online friends.
> Added: 2016/03/19 15:39:17 -> 0 to the spreadsheet.
> 
> Waiting for Facebook to update friends list... (This takes approximately 3 minutes.)
> Done! Detected 0 online friends.
> Added: 2016/03/19 15:45:17 -> 0 to the spreadsheet.

On windows

**Comment by bhamodi** [comment] 2016-03-21 03:19
Investigating this issue now.

**Comment by bhamodi** [comment] 2016-06-19 05:44
Unable to reproduce now. 👍

**Closed as completed by bhamodi** 2016-06-19 05:44 UTC
